# {{name}}

{{description}}

## Pattern

**{{pattern}}** — {{pattern_rationale}}

## Primitives

- Orchestrator: `/{{orchestrator_name}}` — see `commands/{{orchestrator_name}}.md`
- Sub-agents: {{agents_list}}
- Skills: {{skills_list}}
- MCPs: {{mcps_list}}

## Install

```bash
claude plugin install <path-to-this-directory>
```

## Usage

```
/{{orchestrator_name}} <your input>
```

Generated by `agent-ecosystem-generator` on {{generated_at}}.
